### ISSUE TITLE
Re-naming properties to be closer to their NAR equivalents

### ISSUE THREAD

**Issue by bquinn** [iptc/newsinjson#86]
Philippe suggested that we rename properties to be closer in name to their NewsML-G2 counterparts.

Examples:

|  ninjs 2.0 property | NAR / NewsML-G2 equivalent | Comment | 
| --- | --- | --- |
| uri | newsItem@guid | |
| type | itemClass | Note that itemclass is a concept URI in G2 whereas type is currently an enum in ninjs, and they don't have the same value domain |
| mimetype | contentType | The mimetype / contentType of what ? Should we move it to a property of body ? |
| description/name | description/role| In NAR the role is a concept URI |
| body/name | inline***/rendition| In NAR the rendition is a concept URI |
| headline/name | headline/role| In NAR the role is a concept URI |
| person | subject | That's a bigger issue than difference in naming, as subject in ninjs is untyped |
| organisation | subject | That's a bigger issue than difference in naming, as subject in ninjs is untyped and has no support for the "symbols" property |
| place | subject | That's a bigger issue than difference in naming, as subject in ninjs is untyped and has no support for  geojson |
| object | subject | That's a bigger issue than difference in naming, as subject in ninjs is untyped |
| byline | by | |
| /charcount | inline***/charcount | Should we move it to a property of body ?  |
| /wordcount | inline***/charcount | Should we move it to a property of body ?  |
| renditions | remoteContent | |
| renditions/name | remoteContent/rendition | |
| renditions/sizeinbytes | remoteContent/size | |
| associations | link | I don't think it's the same concept |
| trustindicator | link | |

@pmougin did I miss any? Feel free to edit this table.

Later conversation in this week's call suggested that we don't want to change the property names to things that are more confusing to the average JSON user. So we need to think about that aspect as well before making any changes.

**Comment by pmougin** [comment]
I added a few entries to the table and a comment column.

**Comment by jolla56** [comment]
a) We decided to keep the name uri and the format uri in the json schema. Changing the name and keeping the format seemed strange. And most important was to keep the format of uri. The documentation shall be updated to better explain what the uri property is meant for.
b) We decided to keep type instead of renaming to itemClass and link to ninature vocabulary. It only raises the complexity without solving anything. 
c) mimetype was not discussed.
d) body, description and headline was discussed. Have name+value in all might be wrong. We will look this over and maybe add some properties. A combination of contentType and role instead of name might be better.

1) We decided to remove "name" from descriptions, bodies and headlines. Instead we decided to add "contentType" and "role". Even if contentType might not be that useful for descriptions it felt it was easier to have the same model for all three. But in the documentation for description we should point out that it is primarily for metadata and informational purposes.
With ednote in place we discussed if descriptions is needed at all. But there were several examples of various use of it.

2) We decided to remove mimetype from the top level. It does not do anything there. It is enough with mimetype in renditions. We decided to rename it to contentType to align with contentType in bodies.

3) We decided to keep people, organisations, places and objects as they are and not move them into subjects. This is a feature of ninjs/json and ease of use was a guiding principle for the initial design of ninjs.

2) We continued with issue #86 and the bylines/by question. We decided to align with NAR/NewsMLG2 and change byline to by. 

3) We decided to move charcount and wordcount to the bodies array for each item.

4) We had a big discussion about renditions in ninjs and remoteContent in NewsML-G2. We finally decided to stay with renditions.

5) We decided to keep associations and trustinidicators and not move to a generic link property. But the documentation should be updated in ninjs.
